name: Build and push r-debug

on:
  push:
    branches: [ main ]
    paths: [ r-debug, .github/workflows/r-debug.yml ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build and push image
      run: |
        cd r-debug
        docker build . --tag paleolimbot/r-debug
        echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push paleolimbot/r-debug
